before_script:
  - rvm get head
  # - pod repo update
  # - ( cd swift-protocol-oriented-programming && pod install )
  - gem install xcpretty
language: objective-c                   #Used for Swift or Objective-c
osx_image: xcode11.3
script: set -o pipefail && xcodebuild -project swift-algorithms/swift-algorithms.xcodeproj -scheme swift-algorithms CODE_SIGNING_REQUIRED=NO test | xcpretty
